openapi: 3.0.0
servers:
  - url: https://api.m28.gobizdev.com/external
    description: staging
  - url: https://fulfilment.mygobiz.net/external
    description: production
info:
  description: ubox
  version: "1.0.0"
  title: M28 External API
  contact:
    email: vuduythanh@gobiz.vn
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: merchants
    description: Module merchants calls

paths:
  /merchants:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - merchants
      summary: create a mechant
      operationId: createMerchant
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - code
                - password
                - email
                - location
                - phone
              properties:
                code:
                  type: string
                password:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                location:
                  type: string
                  example:
                    vietnam|thailand
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  merchant:
                    $ref: '#/components/schemas/Merchant'
        '400':
          description: INPUT_INVALID
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  data:
                    type: object
                    properties:
                      domain:
                        type: string
                        example:
                          exists
                      username:
                        type: string
                        example:
                          already_exist
                      location:
                        type: string
                        example:
                          invalid

  /merchants/{merchant_code}/products:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - merchants
      summary: create a product
      operationId: createProduct
      parameters:
        - in: path
          name: merchant_code
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - password
                - re_password
                - email
                - location
              properties:
                name:
                  type: string
                code:
                  type: string
                image:
                  type: string
                  format: binary
                  example:
                    base64image
                weight:
                  type: number
                height:
                  type: number
                width:
                  type: number
                length:
                  type: number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  merchant:
                    $ref: '#/components/schemas/Product'
        '400':
          description: INPUT_INVALID
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  data:
                    type: object
  /merchants/{merchant_code}/products/{product_code}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - merchants
      summary: product detail
      operationId: detailProduct
      parameters:
        - in: path
          name: merchant_code
          required: true
          schema:
            type: string
        - in: path
          name: product_code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  product:
                    $ref: '#/components/schemas/Product'
        '400':
          description: INPUT_INVALID
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  data:
                    type: object
  /merchants/{merchant_code}/products/{product_code}/stocks:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - merchants
      summary: stock of a product
      operationId: stockOfProduct
      parameters:
        - in: path
          name: merchant_code
          required: true
          schema:
            type: string
        - in: path
          name: product_code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  stock:
                    $ref: '#/components/schemas/Stock'
                  warehouse:
                    $ref: '#/components/schemas/Warehouse'
                  warehouse_area:
                    $ref: '#/components/schemas/WarehouseArea'
        '400':
          description: INPUT_INVALID
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  data:
                    type: object
  /merchants/{merchant_code}/orders:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - merchants
      summary: create a order
      operationId: createOrder
      parameters:
        - in: path
          name: merchant_code
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - code
                - receiver_name
                - receiver_address
                - receiver_phone
                - warehouse_code
                - products
              properties:
                code:
                  type: string
                freight_bill:
                  type: string
                receiver_name:
                  type: string
                receiver_address:
                  type: string
                receiver_phone:
                  type: string
                warehouse_code:
                  type: string
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      code:
                        type: string
                      price:
                        type: number
                      quantity:
                        type: number
                      discount_amount:
                        type: number
                shipping_partner_code:
                  type: string
                discount_amount:
                  type: number
                total_amount:
                  type: number
                description:
                  type: string
                receiver_district_code:
                  type: string
                receiver_province_code:
                  type: string
                receiver_ward_code:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    $ref: '#/components/schemas/Order'
        '400':
          description: INPUT_INVALID
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  data:
                    type: object
  /merchants/{merchant_code}/orders/{order_code}:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - merchants
      summary: order detail
      operationId: detailOrder
      parameters:
        - in: path
          name: merchant_code
          required: true
          schema:
            type: string
        - in: path
          name: order_code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    $ref: '#/components/schemas/Order'
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  services:
                    type: array
                    items:
                      $ref: '#/components/schemas/Service'
                  shipping_partner:
                    $ref: '#/components/schemas/ShippingPartner'
                  freight_bills:
                    type: array
                    items:
                      $ref: '#/components/schemas/FreightBill'
                  warehouse:
                    $ref: '#/components/schemas/Warehouse'
        '400':
          description: INPUT_INVALID
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  data:
                    type: object

components:
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Merchant:
      type: object
      properties:
        id:
          type: number
        code:
          type: string
        name:
          type: string
        username:
          type: string
        phone:
          type: string
        address:
          type: string
        ref:
          type: string
        description:
          type: string
        status:
          type: boolean
        created_at:
          type: string
        updated_at:
          type: string

    Product:
      type: object

    Stock:
      type: object

    Order:
      type: object

